import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const forwarderWorkspaceSource = readFileSync(
  new URL('../src/components/ForwarderWorkspace.jsx', import.meta.url),
  'utf8'
);

test('1. ForwarderWorkspace persistProjectToDatabase contains services autogeneration logic', () => {
  // Check persistProjectToDatabase exists
  const persistMatch = forwarderWorkspaceSource.match(
    /const\s+persistProjectToDatabase\s*=\s*async\s*\([^)]*\)\s*=>\s*\{([\s\S]*?)(?:const\s+handleSaveProject|\n\s*return\s+finalSaved;)/
  );
  assert.ok(persistMatch, 'persistProjectToDatabase definition must exist in ForwarderWorkspace.jsx');
  const persistBody = persistMatch[1];

  // 1. Checks servicesList.length === 0 and land freight cost > 0
  assert.match(
    persistBody,
    /servicesList\.length\s*===\s*0\s*&&[\s\S]*?(?:tuVariableDeCosteTotalTerrestre|costeCalculado)/,
    'Must check if servicesList is empty and positive land cost exists'
  );

  // 2. Generates service with srv-auto- id and Flete y Operaciones Terrestres name
  assert.match(
    persistBody,
    /id:\s*['"]srv-auto-['"]\s*\+\s*Date\.now\(\)/,
    'Must generate service id starting with srv-auto- and timestamp'
  );

  assert.match(
    persistBody,
    /name:\s*autoServiceName|name:\s*finalAutoName|name:\s*['"]Flete y Operaciones Terrestres \(['"]/,
    'Must assign service name matching Flete y Operaciones Terrestres format'
  );

  // 3. Sets cost and sale
  assert.match(
    persistBody,
    /cost:\s*(?:costeCalculado|finalAutoCost|calculatedLandCost)/,
    'Must set cost on auto-generated service'
  );
  assert.match(
    persistBody,
    /sale:\s*(?:ventaCalculada|finalAutoSale|calculatedLandSale)/,
    'Must set sale on auto-generated service'
  );

  // 4. Injects service into payload
  assert.match(
    persistBody,
    /services:\s*servicesList/,
    'Payload must bind servicesList'
  );
});

test('2. ForwarderWorkspace table renders autogenerated services with name/description and cost/sale fallbacks', () => {
  assert.match(
    forwarderWorkspaceSource,
    /item\?\.description\s*\|\|\s*item\?\.name\s*\|\|\s*['"]Servicio['"]/,
    'Table td must support both description and name'
  );

  assert.match(
    forwarderWorkspaceSource,
    /item\?\.cost_eur\s*\?\?\s*item\?\.cost\s*\?\?\s*0/,
    'Table td must support cost_eur with fallback to cost'
  );

  assert.match(
    forwarderWorkspaceSource,
    /item\?\.sale_price_eur\s*\?\?\s*item\?\.sale\s*\?\?\s*0/,
    'Table td must support sale_price_eur with fallback to sale'
  );
});

test('3. Behavioral simulation: Autogenerates default service when servicesList is empty and cost > 0', () => {
  // Simulate the exact logic from persistProjectToDatabase
  const projectToSave = {
    project_ref: 'EXP-123456',
    land_origin: 'Madrid',
    land_destination: 'Valencia',
    land_distance: 350,
    total_trucks: 2,
    land_freight_cost: 1100,
    land_freight_sale: 1300,
    services: [],
    line_items: [],
  };

  const servicesList = (Array.isArray(projectToSave?.services) && projectToSave.services.length > 0)
    ? [...projectToSave.services]
    : (Array.isArray(projectToSave?.line_items) && projectToSave.line_items.length > 0 ? [...projectToSave.line_items] : []);

  const distanceKm = Number(projectToSave.land_distance);
  const tuVariableDeCosteTotalTerrestre = 1100;
  const tuVariableDePrecioVentaTerrestre = 1300;
  const costeCalculado = Number(projectToSave?.land_freight_cost) || tuVariableDeCosteTotalTerrestre;
  const ventaCalculada = Number(projectToSave?.land_freight_sale) || tuVariableDePrecioVentaTerrestre;
  const autoTotalTrucks = Number(projectToSave?.total_trucks) || 1;
  const autoLandOrigin = projectToSave?.land_origin || 'Origen';
  const autoLandDestination = projectToSave?.land_destination || 'Destino';

  if (servicesList.length === 0 && !projectToSave?.is_delete_action && (Number(tuVariableDeCosteTotalTerrestre) > 0 || costeCalculado > 0)) {
    const autoServiceName = 'Flete y Operaciones Terrestres (' + (autoTotalTrucks || 1) + ' Camiones: ' + (autoLandOrigin || 'Origen') + ' ➔ ' + (autoLandDestination || 'Destino') + ')';
    const defaultService = {
      id: 'srv-auto-' + Date.now(),
      name: autoServiceName,
      description: autoServiceName,
      cost: costeCalculado,
      sale: ventaCalculada,
      cost_eur: costeCalculado,
      sale_price_eur: ventaCalculada,
      margin_eur: Number((ventaCalculada - costeCalculado).toFixed(2)),
      land_freight_cost: costeCalculado,
      land_freight_sale: ventaCalculada,
    };
    servicesList.push(defaultService);
  }

  assert.equal(servicesList.length, 1, 'servicesList should have 1 auto-generated service');
  assert.match(servicesList[0].id, /^srv-auto-\d+$/);
  assert.equal(servicesList[0].name, 'Flete y Operaciones Terrestres (2 Camiones: Madrid ➔ Valencia)');
  assert.equal(servicesList[0].cost, 1100);
  assert.equal(servicesList[0].sale, 1300);
  assert.equal(servicesList[0].cost_eur, 1100);
  assert.equal(servicesList[0].sale_price_eur, 1300);
});

test('4. Behavioral simulation: Preserves existing services without adding duplicate auto-service', () => {
  const existingService = {
    id: 'srv-manual-1',
    description: 'Transporte Especial',
    cost_eur: 500,
    sale_price_eur: 750,
  };

  const projectToSave = {
    land_origin: 'Sevilla',
    land_destination: 'Cádiz',
    land_distance: 120,
    land_freight_cost: 500,
    land_freight_sale: 750,
    services: [existingService],
  };

  const servicesList = (Array.isArray(projectToSave?.services) && projectToSave.services.length > 0)
    ? [...projectToSave.services]
    : [];

  const tuVariableDeCosteTotalTerrestre = 500;
  const costeCalculado = 500;

  if (servicesList.length === 0 && !projectToSave?.is_delete_action && (Number(tuVariableDeCosteTotalTerrestre) > 0 || costeCalculado > 0)) {
    servicesList.push({ id: 'srv-auto-' + Date.now() });
  }

  assert.equal(servicesList.length, 1);
  assert.equal(servicesList[0].id, 'srv-manual-1');
});

test('5. persistProjectToDatabase autogenerates Flete Terrestre line item before fetch into payload.services and payload.line_items', () => {
  // Verifies check for empty services or line_items and land_freight_cost > 0
  assert.match(
    forwarderWorkspaceSource,
    /(?:isServicesEmpty|!payload\.services\s*\|\|\s*payload\.services\.length\s*===\s*0)[\s\S]*?Number\(payload\.land_freight_cost\)\s*>\s*0/,
    'Must check if payload.services or payload.line_items is empty with land_freight_cost > 0'
  );

  // Verifies name format 'Flete Terrestre (' + (payload.total_trucks || 1) + ' Camiones: ' + (payload.land_origin || 'Origen') + ' ➔ ' + (payload.land_destination || 'Destino') + ')'
  assert.match(
    forwarderWorkspaceSource,
    /name:\s*['"]Flete Terrestre \(['"]\s*\+\s*\(payload\.total_trucks\s*\|\|\s*1\)\s*\+\s*['"] Camiones: ['"]\s*\+\s*\(payload\.land_origin\s*\|\|\s*['"]Origen['"]\)\s*\+\s*['"] ➔ ['"]\s*\+\s*\(payload\.land_destination\s*\|\|\s*['"]Destino['"]\)\s*\+\s*['"]\)['"]/,
    'Must format service name as Flete Terrestre with trucks count, origin and destination'
  );

  // Verifies push into payload.services and payload.line_items
  assert.match(
    forwarderWorkspaceSource,
    /payload\.services\.push\(autoService\)/,
    'Must push autoService into payload.services'
  );
  assert.match(
    forwarderWorkspaceSource,
    /payload\.line_items\.push\(autoService\)/,
    'Must push autoService into payload.line_items'
  );
});

test('6. persistProjectToDatabase calculates valor_total_mercancia_usd from items and GICA cement catalog', () => {
  // Verifies calculation of valorCalculadoDeItems from cargoArrayForFob
  assert.match(
    forwarderWorkspaceSource,
    /const\s+estadoDelValorFobCalculado\s*=\s*Number\(mercanciaCost\)/,
    'Must evaluate estadoDelValorFobCalculado from mercanciaCost'
  );
  assert.match(
    forwarderWorkspaceSource,
    /let\s+valorCalculadoDeItems\s*=\s*0;/,
    'Must initialize valorCalculadoDeItems'
  );
  assert.match(
    forwarderWorkspaceSource,
    /valor_total_mercancia_usd:\s*Number\(estadoDelValorFobCalculado\)\s*\|\|\s*Number\(valorCalculadoDeItems\)\s*\|\|\s*Number\(projectToSave\.valor_total_mercancia_usd\)\s*\|\|\s*0/,
    'Must assign valor_total_mercancia_usd using estadoDelValorFobCalculado, valorCalculadoDeItems, projectToSave fallback'
  );
});

test('7. Behavioral simulation: GICA cement catalog items calculate dynamic FOB value', () => {
  const COMMODITY_VALUES = {
    'CEM I 52,5N BIGBAG': 60,
    'CEM I 42,5N/R BIGBAG': 55,
    'CEM II 42,5 VRAC': 50,
  };

  const cargoItems = [
    { type: 'CEM I 52,5N BIGBAG', quantity: 100, weight: 1500 }, // 150 MT * 60 = 9,000 USD
    { type: 'CEM II 42,5 VRAC', quantity: 1, weight_tons: 200 },    // 200 MT * 50 = 10,000 USD
  ];

  const valorCalculadoDeItems = cargoItems.reduce((acc, item) => {
    const rawType = item.type;
    const qty = item.quantity || 1;
    const pieceWeight = Number(item.weight || 0);
    const itemTotalKg = pieceWeight > 0 ? (qty * pieceWeight) : 0;
    const weightTons = itemTotalKg > 0 ? (itemTotalKg / 1000) : (Number(item.weight_tons) || 0);
    const unitPrice = COMMODITY_VALUES[rawType] || 0;
    return acc + (weightTons * unitPrice);
  }, 0);

  assert.equal(valorCalculadoDeItems, 19000, 'Total FOB value should be 19,000 USD');

  const estadoDelValorFobCalculado = 0;
  const projectToSave = { valor_total_mercancia_usd: 0 };
  const valorTotalMercanciaUsd = Number(estadoDelValorFobCalculado) || Number(valorCalculadoDeItems) || Number(projectToSave.valor_total_mercancia_usd) || 0;

  assert.equal(valorTotalMercanciaUsd, 19000, 'Payload valor_total_mercancia_usd must resolve to 19000');
});
