import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const forwarderWorkspaceSource = readFileSync(
  new URL('../src/components/ForwarderWorkspace.jsx', import.meta.url),
  'utf8'
);

test('1. ForwarderWorkspace persistProjectToDatabase contains services autogeneration logic', () => {
  // Check persistProjectToDatabase exists
  const persistMatch = forwarderWorkspaceSource.match(
    /const\s+persistProjectToDatabase\s*=\s*async\s*\([^)]*\)\s*=>\s*\{([\s\S]*?)(?:const\s+handleSaveProject|\n\s*return\s+finalSaved;)/
  );
  assert.ok(persistMatch, 'persistProjectToDatabase definition must exist in ForwarderWorkspace.jsx');
  const persistBody = persistMatch[1];

  // 1. Checks servicesList.length === 0 and land freight cost > 0
  assert.match(
    persistBody,
    /servicesList\.length\s*===\s*0\s*&&[\s\S]*?(?:tuVariableDeCosteTotalTerrestre|costeCalculado)/,
    'Must check if servicesList is empty and positive land cost exists'
  );

  // 2. Generates service with srv-auto- id and Flete y Operaciones Terrestres name
  assert.match(
    persistBody,
    /id:\s*['"]srv-auto-['"]\s*\+\s*Date\.now\(\)/,
    'Must generate service id starting with srv-auto- and timestamp'
  );

  assert.match(
    persistBody,
    /name:\s*autoServiceName|name:\s*finalAutoName|name:\s*['"]Flete y Operaciones Terrestres \(['"]/,
    'Must assign service name matching Flete y Operaciones Terrestres format'
  );

  // 3. Sets cost and sale
  assert.match(
    persistBody,
    /cost:\s*(?:costeCalculado|finalAutoCost|calculatedLandCost)/,
    'Must set cost on auto-generated service'
  );
  assert.match(
    persistBody,
    /sale:\s*(?:ventaCalculada|finalAutoSale|calculatedLandSale)/,
    'Must set sale on auto-generated service'
  );

  // 4. Injects service into payload
  assert.match(
    persistBody,
    /services:\s*servicesList/,
    'Payload must bind servicesList'
  );
});

test('2. ForwarderWorkspace table renders autogenerated services with name/description and cost/sale fallbacks', () => {
  assert.match(
    forwarderWorkspaceSource,
    /item\?\.description\s*\|\|\s*item\?\.name\s*\|\|\s*['"]Servicio['"]/,
    'Table td must support both description and name'
  );

  assert.match(
    forwarderWorkspaceSource,
    /item\?\.cost_eur\s*\?\?\s*item\?\.cost\s*\?\?\s*0/,
    'Table td must support cost_eur with fallback to cost'
  );

  assert.match(
    forwarderWorkspaceSource,
    /item\?\.sale_price_eur\s*\?\?\s*item\?\.sale\s*\?\?\s*0/,
    'Table td must support sale_price_eur with fallback to sale'
  );
});

test('3. Behavioral simulation: Autogenerates default service when servicesList is empty and cost > 0', () => {
  // Simulate the exact logic from persistProjectToDatabase
  const projectToSave = {
    project_ref: 'EXP-123456',
    land_origin: 'Madrid',
    land_destination: 'Valencia',
    land_distance: 350,
    total_trucks: 2,
    land_freight_cost: 1100,
    land_freight_sale: 1300,
    services: [],
    line_items: [],
  };

  const servicesList = (Array.isArray(projectToSave?.services) && projectToSave.services.length > 0)
    ? [...projectToSave.services]
    : (Array.isArray(projectToSave?.line_items) && projectToSave.line_items.length > 0 ? [...projectToSave.line_items] : []);

  const distanceKm = Number(projectToSave.land_distance);
  const tuVariableDeCosteTotalTerrestre = 1100;
  const tuVariableDePrecioVentaTerrestre = 1300;
  const costeCalculado = Number(projectToSave?.land_freight_cost) || tuVariableDeCosteTotalTerrestre;
  const ventaCalculada = Number(projectToSave?.land_freight_sale) || tuVariableDePrecioVentaTerrestre;
  const autoTotalTrucks = Number(projectToSave?.total_trucks) || 1;
  const autoLandOrigin = projectToSave?.land_origin || 'Origen';
  const autoLandDestination = projectToSave?.land_destination || 'Destino';

  if (servicesList.length === 0 && !projectToSave?.is_delete_action && (Number(tuVariableDeCosteTotalTerrestre) > 0 || costeCalculado > 0)) {
    const autoServiceName = 'Flete y Operaciones Terrestres (' + (autoTotalTrucks || 1) + ' Camiones: ' + (autoLandOrigin || 'Origen') + ' ➔ ' + (autoLandDestination || 'Destino') + ')';
    const defaultService = {
      id: 'srv-auto-' + Date.now(),
      name: autoServiceName,
      description: autoServiceName,
      cost: costeCalculado,
      sale: ventaCalculada,
      cost_eur: costeCalculado,
      sale_price_eur: ventaCalculada,
      margin_eur: Number((ventaCalculada - costeCalculado).toFixed(2)),
      land_freight_cost: costeCalculado,
      land_freight_sale: ventaCalculada,
    };
    servicesList.push(defaultService);
  }

  assert.equal(servicesList.length, 1, 'servicesList should have 1 auto-generated service');
  assert.match(servicesList[0].id, /^srv-auto-\d+$/);
  assert.equal(servicesList[0].name, 'Flete y Operaciones Terrestres (2 Camiones: Madrid ➔ Valencia)');
  assert.equal(servicesList[0].cost, 1100);
  assert.equal(servicesList[0].sale, 1300);
  assert.equal(servicesList[0].cost_eur, 1100);
  assert.equal(servicesList[0].sale_price_eur, 1300);
});

test('4. Behavioral simulation: Preserves existing services without adding duplicate auto-service', () => {
  const existingService = {
    id: 'srv-manual-1',
    description: 'Transporte Especial',
    cost_eur: 500,
    sale_price_eur: 750,
  };

  const projectToSave = {
    land_origin: 'Sevilla',
    land_destination: 'Cádiz',
    land_distance: 120,
    land_freight_cost: 500,
    land_freight_sale: 750,
    services: [existingService],
  };

  const servicesList = (Array.isArray(projectToSave?.services) && projectToSave.services.length > 0)
    ? [...projectToSave.services]
    : [];

  const tuVariableDeCosteTotalTerrestre = 500;
  const costeCalculado = 500;

  if (servicesList.length === 0 && !projectToSave?.is_delete_action && (Number(tuVariableDeCosteTotalTerrestre) > 0 || costeCalculado > 0)) {
    servicesList.push({ id: 'srv-auto-' + Date.now() });
  }

  assert.equal(servicesList.length, 1);
  assert.equal(servicesList[0].id, 'srv-manual-1');
});
